variable "group" {
  type = map(object({
    vpc_id                            = optional(string)
    security_group_ids                = optional(list(string))
    subnet_ids                        = optional(list(string))
    internal                          = optional(bool)
    http_enabled                      = optioanl(bool)
    http_redirect                     = optional(bool)
    https_enabled                     = optional(bool)
    access_logs_enabled               = optional(bool)
    cross_zone_load_balancing_enabled = optional(bool)
    http2_enabled                     = optional(bool)
    idle_timeout                      = optional(number)
    ip_address_type                   = optional(string)
    deletion_protection_enabled       = optional(bool)
    deregistration_delay              = optional(number)
    health_check_path                 = optional(string)
    health_check_timeout              = optional(number)
    health_check_healthy_threshold    = optional(number)
    health_check_unhealthy_threshold  = optional(number)
    health_check_interval             = optional(number)
    health_check_matcher              = optional(string)
    target_group_port                 = optional(number)
    target_group_target_type          = optional(string)
    stickiness                        = optional(object)
    certificate_arn                   = optional(string)

    alb_access_logs_s3_bucket_force_destroy         = optional(bool)
    alb_access_logs_s3_bucket_force_destroy_enabled = optional(bool)
  }))
}